// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: internal/grpc/textNote/textNote.proto

package grpc_textNote

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextNoteEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NoteTextHash string `protobuf:"bytes,2,opt,name=note_text_hash,json=noteTextHash,proto3" json:"note_text_hash,omitempty"`
	NoteName     string `protobuf:"bytes,3,opt,name=note_name,json=noteName,proto3" json:"note_name,omitempty"`
	EntryHash    string `protobuf:"bytes,4,opt,name=entry_hash,json=entryHash,proto3" json:"entry_hash,omitempty"`
}

func (x *TextNoteEntry) Reset() {
	*x = TextNoteEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_textNote_textNote_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextNoteEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextNoteEntry) ProtoMessage() {}

func (x *TextNoteEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_textNote_textNote_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextNoteEntry.ProtoReflect.Descriptor instead.
func (*TextNoteEntry) Descriptor() ([]byte, []int) {
	return file_internal_grpc_textNote_textNote_proto_rawDescGZIP(), []int{0}
}

func (x *TextNoteEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TextNoteEntry) GetNoteTextHash() string {
	if x != nil {
		return x.NoteTextHash
	}
	return ""
}

func (x *TextNoteEntry) GetNoteName() string {
	if x != nil {
		return x.NoteName
	}
	return ""
}

func (x *TextNoteEntry) GetEntryHash() string {
	if x != nil {
		return x.EntryHash
	}
	return ""
}

type ExistingTextNoteHash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EntryHash string `protobuf:"bytes,2,opt,name=entry_hash,json=entryHash,proto3" json:"entry_hash,omitempty"`
}

func (x *ExistingTextNoteHash) Reset() {
	*x = ExistingTextNoteHash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_textNote_textNote_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExistingTextNoteHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistingTextNoteHash) ProtoMessage() {}

func (x *ExistingTextNoteHash) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_textNote_textNote_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistingTextNoteHash.ProtoReflect.Descriptor instead.
func (*ExistingTextNoteHash) Descriptor() ([]byte, []int) {
	return file_internal_grpc_textNote_textNote_proto_rawDescGZIP(), []int{1}
}

func (x *ExistingTextNoteHash) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExistingTextNoteHash) GetEntryHash() string {
	if x != nil {
		return x.EntryHash
	}
	return ""
}

type ListTextNoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExistingHashes []*ExistingTextNoteHash `protobuf:"bytes,1,rep,name=existing_hashes,json=existingHashes,proto3" json:"existing_hashes,omitempty"`
}

func (x *ListTextNoteRequest) Reset() {
	*x = ListTextNoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_textNote_textNote_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTextNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTextNoteRequest) ProtoMessage() {}

func (x *ListTextNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_textNote_textNote_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTextNoteRequest.ProtoReflect.Descriptor instead.
func (*ListTextNoteRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_textNote_textNote_proto_rawDescGZIP(), []int{2}
}

func (x *ListTextNoteRequest) GetExistingHashes() []*ExistingTextNoteHash {
	if x != nil {
		return x.ExistingHashes
	}
	return nil
}

type ListTextNoteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string           `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Notes []*TextNoteEntry `protobuf:"bytes,2,rep,name=notes,proto3" json:"notes,omitempty"`
}

func (x *ListTextNoteResponse) Reset() {
	*x = ListTextNoteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_textNote_textNote_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTextNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTextNoteResponse) ProtoMessage() {}

func (x *ListTextNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_textNote_textNote_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTextNoteResponse.ProtoReflect.Descriptor instead.
func (*ListTextNoteResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_textNote_textNote_proto_rawDescGZIP(), []int{3}
}

func (x *ListTextNoteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ListTextNoteResponse) GetNotes() []*TextNoteEntry {
	if x != nil {
		return x.Notes
	}
	return nil
}

type CreateTextNoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NoteTextHash string `protobuf:"bytes,1,opt,name=note_text_hash,json=noteTextHash,proto3" json:"note_text_hash,omitempty"`
	NoteName     string `protobuf:"bytes,2,opt,name=note_name,json=noteName,proto3" json:"note_name,omitempty"`
}

func (x *CreateTextNoteRequest) Reset() {
	*x = CreateTextNoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_textNote_textNote_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTextNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTextNoteRequest) ProtoMessage() {}

func (x *CreateTextNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_textNote_textNote_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTextNoteRequest.ProtoReflect.Descriptor instead.
func (*CreateTextNoteRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_textNote_textNote_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTextNoteRequest) GetNoteTextHash() string {
	if x != nil {
		return x.NoteTextHash
	}
	return ""
}

func (x *CreateTextNoteRequest) GetNoteName() string {
	if x != nil {
		return x.NoteName
	}
	return ""
}

type CreateTextNoteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Id    string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateTextNoteResponse) Reset() {
	*x = CreateTextNoteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_textNote_textNote_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTextNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTextNoteResponse) ProtoMessage() {}

func (x *CreateTextNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_textNote_textNote_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTextNoteResponse.ProtoReflect.Descriptor instead.
func (*CreateTextNoteResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_textNote_textNote_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTextNoteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateTextNoteResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateTextNoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NoteTextHash string `protobuf:"bytes,2,opt,name=note_text_hash,json=noteTextHash,proto3" json:"note_text_hash,omitempty"`
	NoteName     string `protobuf:"bytes,3,opt,name=note_name,json=noteName,proto3" json:"note_name,omitempty"`
	PreviousHash string `protobuf:"bytes,4,opt,name=previous_hash,json=previousHash,proto3" json:"previous_hash,omitempty"`
	IsDeleted    bool   `protobuf:"varint,5,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	ForceUpdate  bool   `protobuf:"varint,6,opt,name=force_update,json=forceUpdate,proto3" json:"force_update,omitempty"`
}

func (x *UpdateTextNoteRequest) Reset() {
	*x = UpdateTextNoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_textNote_textNote_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTextNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTextNoteRequest) ProtoMessage() {}

func (x *UpdateTextNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_textNote_textNote_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTextNoteRequest.ProtoReflect.Descriptor instead.
func (*UpdateTextNoteRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_textNote_textNote_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTextNoteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTextNoteRequest) GetNoteTextHash() string {
	if x != nil {
		return x.NoteTextHash
	}
	return ""
}

func (x *UpdateTextNoteRequest) GetNoteName() string {
	if x != nil {
		return x.NoteName
	}
	return ""
}

func (x *UpdateTextNoteRequest) GetPreviousHash() string {
	if x != nil {
		return x.PreviousHash
	}
	return ""
}

func (x *UpdateTextNoteRequest) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *UpdateTextNoteRequest) GetForceUpdate() bool {
	if x != nil {
		return x.ForceUpdate
	}
	return false
}

type UpdateTextNoteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *UpdateTextNoteResponse) Reset() {
	*x = UpdateTextNoteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_textNote_textNote_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTextNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTextNoteResponse) ProtoMessage() {}

func (x *UpdateTextNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_textNote_textNote_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTextNoteResponse.ProtoReflect.Descriptor instead.
func (*UpdateTextNoteResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_textNote_textNote_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTextNoteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_grpc_textNote_textNote_proto protoreflect.FileDescriptor

var file_internal_grpc_textNote_textNote_proto_rawDesc = []byte{
	0x0a, 0x25, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x74, 0x65, 0x78, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x2f, 0x74, 0x65, 0x78, 0x74, 0x4e, 0x6f, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x81, 0x01, 0x0a, 0x0d, 0x54, 0x65, 0x78, 0x74,
	0x4e, 0x6f, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x6e, 0x6f, 0x74,
	0x65, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x6e, 0x6f, 0x74, 0x65, 0x54, 0x65, 0x78, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12,
	0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x74, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x65, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x48, 0x61, 0x73, 0x68, 0x22, 0x45, 0x0a, 0x14, 0x45,
	0x78, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x65, 0x78, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x48,
	0x61, 0x73, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x48, 0x61,
	0x73, 0x68, 0x22, 0x55, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x78, 0x74, 0x4e, 0x6f,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x0f, 0x65, 0x78, 0x69,
	0x73, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x45, 0x78, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x65, 0x78,
	0x74, 0x4e, 0x6f, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x52, 0x0e, 0x65, 0x78, 0x69, 0x73, 0x74,
	0x69, 0x6e, 0x67, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x22, 0x52, 0x0a, 0x14, 0x4c, 0x69, 0x73,
	0x74, 0x54, 0x65, 0x78, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x24, 0x0a, 0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x4e, 0x6f, 0x74,
	0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x22, 0x5a, 0x0a,
	0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x78, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x6e, 0x6f, 0x74, 0x65, 0x5f, 0x74,
	0x65, 0x78, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x6e, 0x6f, 0x74, 0x65, 0x54, 0x65, 0x78, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1b, 0x0a, 0x09,
	0x6e, 0x6f, 0x74, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6e, 0x6f, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3e, 0x0a, 0x16, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x65, 0x78, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xd1, 0x01, 0x0a, 0x15, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x78, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x6e, 0x6f, 0x74, 0x65, 0x5f, 0x74, 0x65, 0x78, 0x74,
	0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x6f, 0x74,
	0x65, 0x54, 0x65, 0x78, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x74,
	0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f,
	0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f,
	0x75, 0x73, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70,
	0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x69,
	0x73, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x69, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x6f,
	0x72, 0x63, 0x65, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0b, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x2e, 0x0a,
	0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x78, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0xcd, 0x01,
	0x0a, 0x08, 0x54, 0x65, 0x78, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x4c, 0x69,
	0x73, 0x74, 0x54, 0x65, 0x78, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x54, 0x65, 0x78, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x78, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x65, 0x78, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x65, 0x78, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x17, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x78, 0x74, 0x4e, 0x6f,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x78, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x78, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x78,
	0x74, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0f, 0x5a,
	0x0d, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_grpc_textNote_textNote_proto_rawDescOnce sync.Once
	file_internal_grpc_textNote_textNote_proto_rawDescData = file_internal_grpc_textNote_textNote_proto_rawDesc
)

func file_internal_grpc_textNote_textNote_proto_rawDescGZIP() []byte {
	file_internal_grpc_textNote_textNote_proto_rawDescOnce.Do(func() {
		file_internal_grpc_textNote_textNote_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_grpc_textNote_textNote_proto_rawDescData)
	})
	return file_internal_grpc_textNote_textNote_proto_rawDescData
}

var file_internal_grpc_textNote_textNote_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_grpc_textNote_textNote_proto_goTypes = []interface{}{
	(*TextNoteEntry)(nil),          // 0: TextNoteEntry
	(*ExistingTextNoteHash)(nil),   // 1: ExistingTextNoteHash
	(*ListTextNoteRequest)(nil),    // 2: ListTextNoteRequest
	(*ListTextNoteResponse)(nil),   // 3: ListTextNoteResponse
	(*CreateTextNoteRequest)(nil),  // 4: CreateTextNoteRequest
	(*CreateTextNoteResponse)(nil), // 5: CreateTextNoteResponse
	(*UpdateTextNoteRequest)(nil),  // 6: UpdateTextNoteRequest
	(*UpdateTextNoteResponse)(nil), // 7: UpdateTextNoteResponse
}
var file_internal_grpc_textNote_textNote_proto_depIdxs = []int32{
	1, // 0: ListTextNoteRequest.existing_hashes:type_name -> ExistingTextNoteHash
	0, // 1: ListTextNoteResponse.notes:type_name -> TextNoteEntry
	2, // 2: TextNote.ListTextNote:input_type -> ListTextNoteRequest
	4, // 3: TextNote.CreateTextNote:input_type -> CreateTextNoteRequest
	6, // 4: TextNote.UpdateTextNote:input_type -> UpdateTextNoteRequest
	3, // 5: TextNote.ListTextNote:output_type -> ListTextNoteResponse
	5, // 6: TextNote.CreateTextNote:output_type -> CreateTextNoteResponse
	7, // 7: TextNote.UpdateTextNote:output_type -> UpdateTextNoteResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_grpc_textNote_textNote_proto_init() }
func file_internal_grpc_textNote_textNote_proto_init() {
	if File_internal_grpc_textNote_textNote_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_grpc_textNote_textNote_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextNoteEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_textNote_textNote_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExistingTextNoteHash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_textNote_textNote_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTextNoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_textNote_textNote_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTextNoteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_textNote_textNote_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTextNoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_textNote_textNote_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTextNoteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_textNote_textNote_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTextNoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_textNote_textNote_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTextNoteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_grpc_textNote_textNote_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_textNote_textNote_proto_goTypes,
		DependencyIndexes: file_internal_grpc_textNote_textNote_proto_depIdxs,
		MessageInfos:      file_internal_grpc_textNote_textNote_proto_msgTypes,
	}.Build()
	File_internal_grpc_textNote_textNote_proto = out.File
	file_internal_grpc_textNote_textNote_proto_rawDesc = nil
	file_internal_grpc_textNote_textNote_proto_goTypes = nil
	file_internal_grpc_textNote_textNote_proto_depIdxs = nil
}
